/**
 * Autogenerated by Thrift for Example.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_data_h.h>

#include "Example_types.h"

namespace apache { namespace thrift {

}} // apache::thrift
