/**
 * Autogenerated by Thrift for ../Example.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once
#include "../gen-cpp2/Example_for_each_field.h"
#include "../gen-cpp2/Example_visit_union.h"
