/**
 * Autogenerated by Thrift for Example.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "Example_types.h"
#include "Example_types.tcc"

#include <thrift/lib/cpp2/gen/module_types_cpp.h>

#include "Example_data.h"

