/**
 * Autogenerated by Thrift for ../Example.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "../gen-cpp2/Example_types.h"

namespace cpp2 {

struct Example_constants {

};

} // cpp2
