/**
 * Autogenerated by Thrift for Example.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once
#include "Example_for_each_field.h"
#include "Example_visit_union.h"
#include "Example_visit_by_thrift_field_metadata.h"
