/**
 * Autogenerated by Thrift for Example.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "KarolService.h"
#include "KarolService.tcc"

namespace cpp2 {
} // cpp2
