/**
 * Autogenerated by Thrift for ../Example.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include "../gen-cpp2/KarolService.h"
#include "../gen-cpp2/KarolService.tcc"

namespace cpp2 {
} // cpp2
